### ISSUE TITLE
Spelling error?

### ISSUE THREAD

**Issue by angoca** [rodneykrick/db2-sql-cookbook#11]
In section 3.5.5, there is this text:

> The new field name must not be qualified (e.g. A.C1), but need not be unique.

The final part should be "but neet to be unique", shouldn't it?

**Comment by rodneykrick** [comment]
No, it shouldn't :-) It doesn't make send to rename columns using the same name, but it is allowed (Db2 allows it). 
You can change the original code:
SELECT EMPNO AS E_NUM, MIDINIT AS "m int", PHONENO AS "..."
  FROM DB2INST1.EMPLOYEE
  WHERE EMPNO < '000030'
  ORDER BY 1;

to 

SELECT EMPNO AS "m int", MIDINIT AS "m int", PHONENO AS "m int"
  FROM DB2INST1.EMPLOYEE
  WHERE EMPNO < '000030'
  ORDER BY 1;

and it will work. You only will have a problem if you try to use such kind of rename in a view definition, this is not allowed because the combination schema.table.column must be unique in the catalog.

**Comment by rodneykrick** [comment]
Code is correct, although it doesn't make sense to use this kind of "feature".
